# se qualcosa non funziona, è forse perchè compose usa i cont che già ha buildato dal dockerfile vecchio,
# non li ricrea onTheFly dal dockerfile ogni volta

# docker rm treni_web_1
# docker rmi treni_web
# docker-compose up
version: "3.7"
services:
  mysqlz:
    image: mysql:5.5.62
    networks:
      - db-pma-net
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./mysqlz.sql:/docker-entrypoint-initdb.d/dummy1.sql
    ports:
      - "3307:3306"
      # ports: \ X:Y per connettermi dall'interno del network a lui uso Y e dall'host la porta X
  web:
    depends_on:
      - mysqlz
    networks:
      - db-pma-net
    build:
      context: .
      target: prod #lo tolgo se uso prod
    volumes: #lo tolgo se uso prod
      - .:/work #lo tolgo se uso prod
    ports:
      - "3000:3000"
#tolgo il servizio phpmyadmin per prod
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    networks:
      - db-pma-net
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysqlz
      PMA_PASSWORD: my-secret-pw
      PMA_USER: root
    depends_on:
      - mysqlz
      #servizi che aspetta sinconamente

networks:
  db-pma-net:
